# Version catalog is a central place for you to declare and version dependencies
# https://docs.gradle.org/current/userguide/platforms.html#sub:version-catalog
# https://docs.gradle.org/current/userguide/platforms.html#sub::toml-dependencies-format

[versions]
kotlin = "2.3.0"
shadow = "9.3.0"
nightConfig = "3.10.1"

[libraries]
kotlinGradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
shadowGradlePlugin = { module = "com.gradleup.shadow:shadow-gradle-plugin", version.ref = "shadow" }
#
nightConfigCore = { module = "re.neotamia.night-config:core", version.ref = "nightConfig" }
nightConfigToml = { module = "re.neotamia.night-config:toml", version.ref = "nightConfig" }
nightConfigYaml = { module = "re.neotamia.night-config:yaml", version.ref = "nightConfig" }
nightConfigJson = { module = "re.neotamia.night-config:json", version.ref = "nightConfig" }
nightConfigHocon = { module = "re.neotamia.night-config:hocon", version.ref = "nightConfig" }

# Libraries can be bundled together for easier import
[bundles]
jsonModule = ["nightConfigJson"]
yamlModule = ["nightConfigYaml"]
tomlModule = ["nightConfigToml"]
nightConfigModule = ["nightConfigCore", "nightConfigToml", "nightConfigYaml", "nightConfigJson", "nightConfigHocon"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

